import os
import re
import webbrowser
from datetime import datetime
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle
import plotly.graph_objects as go

# =====================================================================
# CONFIGURATION
# =====================================================================
SPOT_BASE_DIR = r"C:\Users\RISHI\nifty_data\nifty_spot"
ALERTS_BASE_DIR = r"C:\Users\RISHI\nifty_data" # Directory where simulation excels are stored
OUTPUT_HTML_DIR = r"C:\Users\RISHI\nifty_data"

# Set the date to visualize (DD_MM_YYYY)
TARGET_OOS_DATE = "30_10_2024"

# Set to True to overlay '>> VOL SPIKE IMMINENT <<' signals if the alert Excel exists
OVERLAY_ALERTS = True

# =====================================================================
# 1. DATA INGESTION & INDEXING
# =====================================================================
def find_spot_file(base_dir, target_date):
    """Locates the spot CSV for target_date across nested directories."""
    for root, _, files in os.walk(base_dir):
        for f in files:
            if f.lower().endswith(".csv") and target_date in f:
                return os.path.join(root, f)
    return None

def find_alerts_file(base_dir, target_date):
    """Searches for simulation alert Excel files generated by the ML pipeline."""
    candidates = [
        f"alerts_{target_date}.xlsx",
        f"nifty_vol_simulation_{target_date}.xlsx",
        f"nifty_vol_alerts_{target_date}.xlsx"
    ]
    for c in candidates:
        full_path = os.path.join(base_dir, c)
        if os.path.exists(full_path):
            return full_path
    return None

def load_session_data(target_date):
    spot_file = find_spot_file(SPOT_BASE_DIR, target_date)
    if not spot_file:
        raise FileNotFoundError(f"No spot CSV found for date {target_date} in {SPOT_BASE_DIR}")
    
    print(f"[{datetime.now().strftime('%H:%M:%S')}] Loading spot data: {spot_file}")
    df = pd.read_csv(spot_file)
    df.columns = [c.strip().lower() for c in df.columns]
    df['time'] = df['time'].astype(str).str.strip()
    
    # Filter NSE market hours (09:15 to 15:30)
    df = df[(df['time'] >= '09:15:00') & (df['time'] <= '15:30:00')].sort_values('time').reset_index(drop=True)
    for col in ['open', 'high', 'low', 'close']:
        df[col] = df[col].astype(float)
        
    # Check for alerts file
    alert_times = []
    if OVERLAY_ALERTS:
        alert_path = find_alerts_file(ALERTS_BASE_DIR, target_date)
        if alert_path:
            print(f"[{datetime.now().strftime('%H:%M:%S')}] Found alert markers: {alert_path}")
            adf = pd.read_excel(alert_path)
            adf.columns = [c.strip().upper() for c in adf.columns]
            status_col = 'ALERT STATUS' if 'ALERT STATUS' in adf.columns else 'ALERT'
            if status_col in adf.columns and 'TIME' in adf.columns:
                spike_rows = adf[adf[status_col].astype(str).str.contains("IMMINENT|SPIKE", case=False, na=False)]
                alert_times = spike_rows['TIME'].astype(str).str.strip().tolist()
                print(f"[{datetime.now().strftime('%H:%M:%S')}] Overlaying {len(alert_times)} imminent volatility triggers.")
                
    return df, alert_times

def resample_data(df, alert_times, target_date, timeframe):
    """Aggregates 1-minute OHLCV data into higher timeframes (e.g., '5min', '15min', '60min')."""
    tf_mapping = {'5': '5min', '15': '15min', '30': '30min', '60': '60min', '1h': '1H'}
    norm_tf = tf_mapping.get(str(timeframe).lower(), timeframe)
    
    # Create datetime index for resampling
    df_copy = df.copy()
    df_copy['dt'] = pd.to_datetime(target_date + ' ' + df_copy['time'], format='%d_%m_%Y %H:%M:%S')
    df_copy.set_index('dt', inplace=True)
    
    # Resample OHLC data
    agg_dict = {'open': 'first', 'high': 'max', 'low': 'min', 'close': 'last'}
    df_resampled = df_copy.resample(norm_tf).agg(agg_dict).dropna().reset_index()
    df_resampled['time'] = df_resampled['dt'].dt.strftime('%H:%M:%S')
    df_resampled.drop(columns=['dt'], inplace=True)
    
    # Map alert times to the corresponding resampled candles
    new_alert_times = []
    if alert_times:
        alert_dts = [pd.to_datetime(target_date + ' ' + t, format='%d_%m_%Y %H:%M:%S') for t in alert_times]
        delta = pd.to_timedelta(norm_tf)
        
        for _, row in df_resampled.iterrows():
            bar_start = pd.to_datetime(target_date + ' ' + row['time'], format='%d_%m_%Y %H:%M:%S')
            bar_end = bar_start + delta
            if any(bar_start <= adt < bar_end for adt in alert_dts):
                new_alert_times.append(row['time'])
                
    return df_resampled, norm_tf, new_alert_times

# =====================================================================
# 2. INTERACTIVE TRADINGVIEW CHART (PLOTLY HTML)
# =====================================================================
def generate_tradingview_html(df, alert_times, target_date, timeframe_label):
    open_p = df['open'].iloc[0]
    high_p = df['high'].max()
    low_p = df['low'].min()
    close_p = df['close'].iloc[-1]
    chg_pts = close_p - open_p
    chg_pct = (chg_pts / open_p) * 100
    chg_color = "#089981" if chg_pts >= 0 else "#F23645"
    sign = "+" if chg_pts >= 0 else ""

    fig = go.Figure()

    # Candlestick Series
    fig.add_trace(go.Candlestick(
        x=df['time'],
        open=df['open'],
        high=df['high'],
        low=df['low'],
        close=df['close'],
        name='NIFTY 50',
        increasing=dict(line=dict(color='#089981', width=1), fillcolor='#089981'),
        decreasing=dict(line=dict(color='#F23645', width=1), fillcolor='#F23645'),
        whiskerwidth=0.8
    ))

    # Overlay Volatility Alerts
    if alert_times:
        alert_df = df[df['time'].isin(alert_times)].copy()
        fig.add_trace(go.Scatter(
            x=alert_df['time'],
            y=alert_df['low'] - 6.0,
            mode='markers',
            name='Vol Spike Imminent',
            marker=dict(symbol='triangle-up', size=11, color='#FF9800', line=dict(width=1, color='#FFFFFF')),
            hoverinfo='text',
            hovertext=[f"<b>⚠️ VOL SPIKE IMMINENT</b><br>Time: {t}<br>Spot: {p:.2f}" for t, p in zip(alert_df['time'], alert_df['close'])]
        ))

    # Last Traded Price (LTP) Reference Line
    fig.add_hline(
        y=close_p,
        line_dash="dash",
        line_color=chg_color,
        line_width=1,
        annotation_text=f" {close_p:.2f}",
        annotation_position="right",
        annotation_font=dict(color="#FFFFFF", size=11),
        annotation_bgcolor=chg_color
    )

    header_html = (
        f"<b>NIFTY 50 · {timeframe_label} · NSE</b>  "
        f"<span style='color:#787B86'>O</span> <span style='color:#D1D4DC'>{open_p:.2f}</span>  "
        f"<span style='color:#787B86'>H</span> <span style='color:#D1D4DC'>{high_p:.2f}</span>  "
        f"<span style='color:#787B86'>L</span> <span style='color:#D1D4DC'>{low_p:.2f}</span>  "
        f"<span style='color:#787B86'>C</span> <span style='color:#D1D4DC'>{close_p:.2f}</span>  "
        f"<span style='color:{chg_color}'>{sign}{chg_pts:.2f} ({sign}{chg_pct:.2f}%)</span>"
    )

    fig.update_layout(
        title=dict(
            text=header_html,
            font=dict(family="-apple-system, BlinkMacSystemFont, 'Trebuchet MS', Roboto, sans-serif", size=13, color="#D1D4DC"),
            x=0.015,
            y=0.98
        ),
        paper_bgcolor='#131722',
        plot_bgcolor='#131722',
        font=dict(color='#787B86', family="-apple-system, BlinkMacSystemFont, 'Trebuchet MS', Roboto, sans-serif"),
        xaxis=dict(
            showgrid=True,
            gridcolor='#1E222D',
            gridwidth=1,
            linecolor='#2A2E39',
            rangeslider=dict(visible=False),
            showline=True,
            zeroline=False,
            showspikes=True,
            spikemode='across',
            spikesnap='cursor',
            spikethickness=1,
            spikedash='dash',
            spikecolor='#787B86',
            tickfont=dict(size=11, color="#787B86")
        ),
        yaxis=dict(
            showgrid=True,
            gridcolor='#1E222D',
            gridwidth=1,
            linecolor='#2A2E39',
            side='right',
            tickformat='.2f',
            showline=True,
            zeroline=False,
            showspikes=True,
            spikemode='across',
            spikesnap='cursor',
            spikethickness=1,
            spikedash='dash',
            spikecolor='#787B86',
            tickfont=dict(size=11, color="#787B86")
        ),
        margin=dict(l=15, r=70, t=45, b=25),
        hovermode='x unified',
        hoverlabel=dict(bgcolor="#1E222D", font_size=12, font_color="#D1D4DC"),
        showlegend=True if alert_times else False,
        legend=dict(x=0.015, y=0.92, font=dict(color="#D1D4DC", size=10), bgcolor="rgba(19, 23, 34, 0.6)")
    )

    out_file = os.path.join(OUTPUT_HTML_DIR, f"tradingview_chart_{target_date}_{timeframe_label}.html")
    fig.write_html(out_file, config={'displayModeBar': True, 'scrollZoom': True})
    print(f"[{datetime.now().strftime('%H:%M:%S')}] Saved TradingView HTML: {out_file}")
    webbrowser.open(out_file)

# =====================================================================
# 3. SPYDER IN-CONSOLE PLOT (MATPLOTLIB)
# =====================================================================
def plot_spyder_native(df, alert_times, target_date, timeframe_label):
    fig, ax = plt.subplots(figsize=(15, 7), facecolor='#131722')
    ax.set_facecolor('#131722')
    
    width = 0.6
    for idx, row in df.iterrows():
        color = '#089981' if row['close'] >= row['open'] else '#F23645'
        # Wick
        ax.plot([idx, idx], [row['low'], row['high']], color=color, linewidth=1.1)
        # Body
        body_bottom = min(row['open'], row['close'])
        body_height = max(abs(row['close'] - row['open']), 0.5)
        ax.add_patch(Rectangle((idx - width/2, body_bottom), width, body_height, facecolor=color, edgecolor=color))
        
    # Plot alert markers
    if alert_times:
        alert_indices = df[df['time'].isin(alert_times)].index
        ax.scatter(alert_indices, df.loc[alert_indices, 'low'] - 6.0, color='#FF9800', marker='^', s=45, zorder=5, label='Vol Alert')

    # Axis styling
    ax.yaxis.tick_right()
    ax.yaxis.set_label_position("right")
    ax.grid(True, color='#1E222D', linestyle='-', linewidth=0.8)
    ax.spines['bottom'].set_color('#2A2E39')
    ax.spines['top'].set_visible(False)
    ax.spines['left'].set_visible(False)
    ax.spines['right'].set_color('#2A2E39')
    ax.tick_params(colors='#787B86', which='both', labelsize=9)

    # Dynamic time labels based on number of candles
    step = max(1, len(df) // 10)
    tick_indices = list(range(0, len(df), step))
    ax.set_xticks(tick_indices)
    ax.set_xticklabels([df['time'].iloc[i][:5] for i in tick_indices])
    ax.set_xlim(-1, len(df))

    open_p, close_p = df['open'].iloc[0], df['close'].iloc[-1]
    chg = close_p - open_p
    sign = "+" if chg >= 0 else ""
    ax.set_title(
        f"NIFTY 50 · {timeframe_label} · NSE ({target_date})   O: {open_p:.2f}  H: {df['high'].max():.2f}  L: {df['low'].min():.2f}  C: {close_p:.2f}  ({sign}{chg:.2f})",
        loc='left', color='#D1D4DC', fontsize=11, fontweight='bold', pad=12
    )

    plt.tight_layout()
    plt.show()

# =====================================================================
# MAIN CONTROLLER
# =====================================================================
def main(timeframe='5min'):
    """
    Main entry point for generating charts with a specified timeframe.
    Examples: main('5min'), main('15min'), main('60min') or main('1H')
    """
    df_raw, alerts_raw = load_session_data(TARGET_OOS_DATE)
    df_session, tf_label, filtered_alerts = resample_data(df_raw, alerts_raw, TARGET_OOS_DATE, timeframe)
    
    plot_spyder_native(df_session, filtered_alerts, TARGET_OOS_DATE, tf_label)
    generate_tradingview_html(df_session, filtered_alerts, TARGET_OOS_DATE, tf_label)

if __name__ == "__main__":
    # You can change this argument to '5min', '15min', '60min', etc.
    main(timeframe='5min')